---

- name: Make folders to hold per-client certs
  file:
    path: /etc/openvpn/client/{{ item }}
    state: directory

- name: Add OpenVPN config for clients
  template:
    src: client.conf
    dest: /etc/openvpn/client/{{ item }}/{{ item }}.conf

- name: Generate certificates for clients
  command: /usr/sbin/openvpn-genclient {{ item }}
  args:
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/private/{{ item }}.key

- name: Copy ta.key for client bundle
  copy:
    remote_src: yes
    src: /etc/easy-rsa/pki/private/ta.key
    dest: /etc/openvpn/client/{{ item }}/ta.key

- name: Copy ca.crt for client bundle
  copy:
    remote_src: yes
    src: /etc/easy-rsa/pki/ca.crt
    dest: /etc/openvpn/client/{{ item }}/ca.crt

- name: Copy client cert for client bundle
  copy:
    remote_src: yes
    src: /etc/easy-rsa/pki/issued/{{ item }}.crt
    dest: /etc/openvpn/client/{{ item }}/client.crt

- name: Copy client key for client bundle
  copy:
    remote_src: yes
    src: /etc/easy-rsa/pki/private/{{ item }}.key
    dest: /etc/openvpn/client/{{ item }}/client.key
