---

- name: Install me an openvpn
  package:
    name: openvpn
    state: present
  tags:
  - rw
  - packages

- name: Grab easy-rsa
  unarchive:
    src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz
    dest: /tmp
    remote_src: yes
  args:
    creates: /tmp/EasyRSA-3.0.8
  tags:
  - rw
  - pki

- name: Move easy-rsa into place
  shell: mv /tmp/EasyRSA-3.0.8/ /etc/easy-rsa
  args:
    creates: /etc/easy-rsa/easyrsa
  tags:
  - rw
  - pki

# Server setup and config
# -------------------------------------

- name: Add a server config
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf
  notify:
  - restart openvpn
  tags:
  - rw
  - config

- name: Add our all-in-one server setup script
  template:
    src: openvpn-serverinit
    dest: /usr/sbin/openvpn-serverinit
    mode: 0755
  tags:
  - rw
  - config
  - pki

- name: Add easy_rsa vars
  template:
    src: easy_rsa_vars
    dest: /etc/easy-rsa/vars
  tags:
  - rw
  - config
  - pki

- name: Generate certificates and keys for server
  command: /usr/sbin/openvpn-serverinit
  args:
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/private/server.key
  notify:
  - restart openvpn
  tags:
  - rw
  - pki


# Client configs
# -------------------------------------

- name: Add our all-in-one client generation script
  template:
    src: openvpn-genclient
    dest: /usr/sbin/openvpn-genclient
    mode: 0755
  tags:
  - rw
  - pki

- include_tasks: add_client.yml
  with_items: "{{ openvpn_client_names }}"


# System stuff
# -------------------------------------

- name: Allow NAT forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
  tags:
  - rw
  - network

- name: Allow OpenVPN through firewall
  firewalld:
    service: openvpn
    state: enabled
    immediate: yes
    permanent: yes
  tags:
  - rw
  - network

- name: Allow NAT masquerade through firewall
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
  tags:
  - rw
  - network

- name: Enable and start OpenVPN
  service:
    name: openvpn@server
    state: started
    enabled: yes
  tags:
  - rw
  - service
